# Generated by Django 5.2.8 on 2026-03-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], max_length=20)),
                ('food', models.CharField(choices=[('Ate Well', 'Ate Well'), ('Ate Little', 'Ate Little'), ('Did Not Eat', 'Did Not Eat')], max_length=20)),
                ('sleep', models.CharField(choices=[('Slept Well', 'Slept Well'), ('Short Nap', 'Short Nap'), ('No Sleep', 'No Sleep')], max_length=20)),
                ('activity_notes', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
