# Generated by Django 5.2.8 on 2026-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_alter_activity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
