# Generated by Django 5.2.8 on 2026-03-20 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0007_alter_class_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='StudentClass',
        ),
        migrations.RenameField(
            model_name='StudentClass',
            old_name='class_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='StudentClass',
            name='class_type',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG')], default='nursery', max_length=20),
        ),
        migrations.AlterField(
            model_name='StudentClass',
            name='teacher',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='food',
            field=models.CharField(blank=True, choices=[('Ate Well', 'Ate Well'), ('Ate Little', 'Ate Little'), ('Did Not Eat', 'Did Not Eat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='sleep',
            field=models.CharField(blank=True, choices=[('Slept Well', 'Slept Well'), ('Short Nap', 'Short Nap'), ('No Sleep', 'No Sleep')], max_length=20, null=True),
        ),
    ]
