# Generated by Django 5.2.8 on 2026-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_alter_dailyreport_food_alter_dailyreport_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/'),
        ),
    ]
